version: "3.9"

services:
  db:
    container_name: mangadbpg_container
    image: postgres:14.0
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-testmangadb}
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASS:-user}
      PGDATA: "/tmp"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER:-user} -d ${DATABASE_NAME:-testmangadb}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - db

  pgadmin:
    container_name: mangadbpgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - db

  mangacms:
    container_name: mangacms_container
    image: ${DOCKER_REGISTRY-}mangacms
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      "Test:SymmetricKey": "0d5b3235a8b403c3dab9c3f4f65c07fcalskd234n1k41230"
#      "ConnectionStrings:MangaCMSDBPG": "Host=host.docker.internal;Port=5432;Database=testmangadb;Username=user;Password=user"
      "ConnectionStrings:MangaCMSDBPG": "Host=db;Port=5432;Database=testmangadb;Username=user;Password=user"
#      "ConnectionStrings:MangaCMSDBPG": "Host=localhost;Port=5432;Database=testmangadb;Username=user;Password=user"
    ports:
    - "3000:80"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db

networks:
  db:
    driver: bridge
